development:
  adapter: postgresql
  encoding: unicode
  database: user_auths_db
  pool: 5
  username: root
  password: root

production:
  adapter: postgresql
  encoding: unicode
  database: user_auths_db
  pool: 5
  username: root
  password: root